name = "cloudflare-docker-proxy3"
compatibility_date = "2023-12-01"
main="./src/index.js"
[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "libcuda.so"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "dp.gppptx.cn"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.dp.gppptx.cn", custom_domain = true },
   { pattern = "quay.dp.gppptx.cn", custom_domain = true },
   { pattern = "gcr.dp.gppptx.cn", custom_domain = true },
   { pattern = "k8s-gcr.dp.gppptx.cn", custom_domain = true },
   { pattern = "k8s.dp.gppptx.cn", custom_domain = true },
   { pattern = "ghcr.dp.gppptx.cn", custom_domain = true },
   { pattern = "cloudsmith.dp.gppptx.cn", custom_domain = true },
 ]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.libcuda.so", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
